name: Lint Posts

on:
  pull_request:
    branches:
      - 'gh-pages'  # Runs when a PR targets the gh-pages branch

jobs:
    lint-posts:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
                cache: npm
            - run: npm ci 
            - run: npm run lint
